### ISSUE TITLE
release version and install version is not same

### ISSUE THREAD

**Issue by KrGil** [Shane-Park/psh#2]
release version is 1.0.0. but install version is master-SNAPSHOT. 
```
dependencies {
    ...
    implementation 'com.github.Shane-Park:psh:master-SNAPSHOT'
}
```
i think it is better to be something like
```
implementation 'com.github.Shane-Park:psh:1.0.0'
```
thank you.

**Comment by ShanePark** [comment]
hi. if i mention exact version name on readme file, i need to update it every time i commit.
but, master-SNAPSHOT always follow the latest commit. Thanks
